[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn api:app --host 0.0.0.0 --port 8000"
restartPolicyType = "on_failure"

[services.api]
public = true

[[services.api.variables]]
HEADLESS = "True"
PYTHONUNBUFFERED = "1"
